const GET_MOVIES ='GET_MOVIES'
const MOVIE_INFO = 'MOVIE_INFO'
const GET_GENRES = 'GET_GENRES'
const GET_MOVIES_OF_GENRE = "GET_MOVIES_OF_GENRE"
const NEXT_PAGE = "NEXT_PAGE"
 const PREVIOUS_PAGE = "PREVIOUS_PAGE"
const  DARK_MODE = "DARK_MODE"
const  TOTAL_PAGES = "TOTAL_PAGES"


export {GET_MOVIES, MOVIE_INFO,GET_GENRES, GET_MOVIES_OF_GENRE, NEXT_PAGE, PREVIOUS_PAGE, DARK_MODE, TOTAL_PAGES}